import {
  EmailIcon,
  FacebookIcon,
  FacebookMessengerIcon,
  GabIcon,
  HatenaIcon,
  InstapaperIcon,
  LineIcon,
  LinkedinIcon,
  LivejournalIcon,
  MailruIcon,
  OKIcon,
  PinterestIcon,
  PocketIcon,
  RedditIcon,
  TelegramIcon,
  ThreadsIcon,
  TumblrIcon,
  TwitterIcon,
  ViberIcon,
  VKIcon,
  WeiboIcon,
  WhatsappIcon,
  WorkplaceIcon,
  XIcon,
  BlueskyIcon,
} from "react-share";

export const socialIcons = [
  { Icon: EmailIcon, name: "Email" },
  { Icon: FacebookIcon, name: "Facebook" },
  { Icon: FacebookMessengerIcon, name: "Messenger" },
  { Icon: GabIcon, name: "Gab" },
  { Icon: HatenaIcon, name: "Hatena" },
  { Icon: InstapaperIcon, name: "Instapaper" },
  { Icon: LineIcon, name: "Line" },
  { Icon: LinkedinIcon, name: "LinkedIn" },
  { Icon: LivejournalIcon, name: "LiveJournal" },
  { Icon: MailruIcon, name: "Mail.ru" },
  { Icon: OKIcon, name: "Odnok" },
  { Icon: PinterestIcon, name: "Pinterest" },
  { Icon: PocketIcon, name: "Pocket" },
  { Icon: RedditIcon, name: "Reddit" },
  { Icon: TelegramIcon, name: "Telegram" },
  { Icon: ThreadsIcon, name: "Threads" },
  { Icon: TumblrIcon, name: "Tumblr" },
  { Icon: TwitterIcon, name: "Twitter" },
  { Icon: ViberIcon, name: "Viber" },
  { Icon: VKIcon, name: "VK" },
  { Icon: WeiboIcon, name: "Weibo" },
  { Icon: WhatsappIcon, name: "WhatsApp" },
  { Icon: WorkplaceIcon, name: "Workplace" },
  { Icon: XIcon, name: "X" },
  { Icon: BlueskyIcon, name: "Bluesky" },
];